name: develop CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: get Github Repository
        uses: actions/checkout@v4

      - name: install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create resources directory if it does not exist
        run: mkdir -p ./src/main/resources

      - name: create application.yml
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: test and build
        run: ./gradlew clean build

      - name: change build file name
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: install sshpass
        run: sudo apt-get install -y sshpass

      - name: Create target directory on EC2
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p /home/reconnect_server/{tobe,current,logs}"

      - name: send build file to EC2 with SCP using password
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no project.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/reconnect_server/tobe

      - name: connect to EC2 with SSH using password
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Remove old current directory
            sudo rm -rf /home/reconnect_server/current || true

            # Create necessary directories
            sudo mkdir -p /home/reconnect_server/{tobe,current,logs}

            # Move the JAR file to the current directory
            sudo mv /home/reconnect_server/tobe/project.jar /home/reconnect_server/current/project.jar

            # Kill any existing process on port 8080
            pid=$(lsof -t -i :8080)
            if [ -n "$pid" ]; then
              echo "Killing process $pid..."
              sudo kill $pid
            else
              echo "No process found on port 8080."
            fi

            # Start the server
            cd /home/reconnect_server/current
            nohup java -jar project.jar --spring.profiles.active=local > /home/reconnect_server/logs/server.log 2>&1 &
            if [ $? -ne 0 ]; then
              echo "Failed to start server process"
              exit 1
            fi

            # Remove old 'tobe' directory
            sudo rm -rf /home/reconnect_server/tobe || true
          EOF
